# Generated by Django 4.2.4 on 2023-09-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='image',
            field=models.ImageField(upload_to='favourites/images'),
        ),
    ]
