# Generated by Django 4.2.4 on 2023-09-14 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_item_color_alter_item_height_alter_item_length_and_more'),
        ('favourites', '0002_alter_favourite_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='main_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.item'),
        ),
    ]
