# Generated by Django 4.2.4 on 2023-09-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_color_item_diameter_item_material_item_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='diameter',
            new_name='length',
        ),
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.IntegerField(default='1'),
        ),
    ]
