# Generated by Django 4.2.4 on 2023-09-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_item_discount_price_item_end_date_item_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
    ]
