# Generated by Django 4.2.4 on 2023-09-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_item_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
