# Generated by Django 4.2.4 on 2023-09-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_purchase_main_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='main_item',
        ),
    ]
